# Use the official Go image as a base
FROM golang:alpine

# Set the working directory to /app
WORKDIR /app

# Copy the Go source code into the container
COPY . /app

# Install any dependencies
RUN go get -d -v ./...

# Build the Go application
RUN go build -o kvstore cmd/kvstore/main.go

# Expose the port that the application will listen on
EXPOSE 50510

# Run the command to start the application when the container is launched
CMD ["./kvstore"]