services:
  kvstore-grpc:
    build:
      context: .
      dockerfile: Dockerfile.kvstore
    env_file: .env
    ports:
      - "${KVSTORE_PORT}:${KVSTORE_PORT}"
    environment:
      - KVSTORE_PORT=${KVSTORE_PORT}

  rest-api:
    build:
      context: .
      dockerfile: Dockerfile.api
    env_file: .env
    ports:
      - "${API_PORT}:${API_PORT}"
    environment:
      - API_PORT=${API_PORT}
    depends_on:
      - kvstore-grpc